rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.1
  - 2.2.3
  - rbx-2
  - ruby-head
  - ree
  - jruby-9.0.0.0
  - jruby-9.0.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.0.0.0
    - rvm: jruby-9.0.1.0
    - rvm: jruby-18mode
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
sudo: false
