#!/usr/bin/env bash

if
  [[ -s "/home/nitrous/code/labs/oo-student-scraper-v-000/.bundle/environment" ]]
then
  source "/home/nitrous/code/labs/oo-student-scraper-v-000/.bundle/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/nitrous/code/labs/oo-student-scraper-v-000/.bundle/environment'" >&2
  exit 1
fi
